### ISSUE TITLE
for infix function, expression [e] has special behavior 

### ISSUE THREAD

**Issue by clojurians-org** [rm-hull/infix#20]
```clojure
    ((fn [{:keys [a e]}] (infix a || e)) {:a false :e true}) => 2.718281828459045
    ((fn [{:keys [a f]}] (infix a || f)) {:a false :f true}) => true
    (infix true || e) => true
```

**Comment by rm-hull** [comment]
`e` is bound to `Math/E` by default (only inside an infix expression).

If you add a call to `(infix.core/suppress! 'e)` somewhere before the macro call, then `e` won't be aliased to `Math/E` anymore:

```clojure
user=> (macroexpand-1 '(infix e * 2))
(* e 2)
```

See #6 for a previous discussion on this.
