### ISSUE TITLE
how to handle == for clojure similar?

### ISSUE THREAD

**Issue by clojurians-org** [rm-hull/infix#21]
(infix 0 == 0.0) => java.lang.Long cannot be cast to clojure.lang.IFn
(infix 0 = 0.0) => false
(== 0 0.0) => true

**Comment by rm-hull** [comment]
Fix should be fairly simple, but I'm away at the moment, back on monday & I'll look at it then

**Comment by rm-hull** [comment]
0.2.10 released to fix this issue - see https://clojars.org/rm-hull/infix/versions/0.2.10
