### ISSUE TITLE
IllegalStateException when calling the function returned from 'from-string', if the first argument of 'from-string' inside the vector is a non literal'

### ISSUE THREAD

**Issue by chrispyl** [rm-hull/infix#22]
I am trying to convert from infix to prefix at runtime. My problem is that when i programmatically put parameters to 'from-string' i get the exception (IllegalStateException x is not bound in environment). The error points at line: 70 in grammar.clj. Here's what i do

The following macro is used to overcome that 'from-string' accepts only vector literals as first parameter

``` clojure
(defmacro from-string-helper [params expression]
    `(from-string [~@params] ~expression))
```

Writing on the repl

``` clojure
(def a (from-string-helper ["x" "y"] "x + y"))
(a 1 1)
```

prints 2 and it's all good. But if i call it from inside another function

``` clojure
(defn create-function [params expression]
    (from-string-helper (seq params) expression)) ;seq, otherwise the compiler doesn't know what to expect in 'from-string-helper' and will complain
```

``` clojure
(def b (create-function ["x" "y"] "x + y"))
(b 1 1)
```

'IllegalStateException x is not bound in environment'. Also, this happens if 'from-string' is directly put inside of a function

``` clojure
(defn create-function [param1 param2 expression]
    (from-string [param1 param2] expression))
```

``` clojure
(def c (create-function "x" "y" "x + y"))
(c 1 1)
```

'IllegalStateException x is not bound in environment'.

Could someone explain why this happens and how it could be fixed?

**Comment by rm-hull** [comment]
I can reproduce the error, but I can’t quite understand how the value is not bound (it has been a long day!), even after expanding all the macros. The `merge` at line 62 here https://github.com/rm-hull/infix/blob/master/src/infix/macros.clj#L62 should merge the environment and the bindings (which appear to be there).

The `from-string` is really intended for creating functions where you already know the arity.

I _think_ you may be able to achieve what you need with something like the following (assuming the right namespaces have been required):

```clojure
(ns infix.example
  (:require
   [jasentaa.parser :refer [parse-all]]
   [infix.core :refer [base-env]]
   [infix.grammar :refer [expression]]))

(defn eval-expr [params expr]
  (if-let [f (parse-all expression expr)]
    (f (merge base-env params))))

(eval-expr {:x 3 :y 4} "x + y")
; => 7
```

or maybe:

```clojure
(defn create-function [expr]
  (if-let [f (parse-all expression expr)]
    (fn [params]
      (f (merge base-env params)))))

(def add (create-function "x + y"))

(add {:x 3 :y 5})
; => 8
```

No need for macros at all!

**Comment by chrispyl** [comment]
Also the following test shows that 'from-string-helper' with non-literal input expands to the same thing as 'from-string' with literal input  
```clojure
(defn testing [params expression]
	(if (empty? params) 
		(from-string-helper [] expression) ;to also check if it works with no arguments
		(do
			(println (= (macroexpand-1 `(from-string-helper ~(vec params) ~expression)) `(from-string ["x" "y" "z"] "x + y + z")))
			(println (macroexpand-1 `(from-string-helper ~(vec params) ~expression)))
			(println `(from-string ["x" "y" "z"] "x + y + z"))
			(def fails (from-string-helper (vec params) expression))
			(def works (from-string ["x" "y" "z"] "x + y + z"))
		)))
```
On the repl
```clojure
(testing ["x" "y" "z"] "x + y + z")
```
outputs
```
true
(infix.macros/from-string [x y z] x + y + z)
(infix.macros/from-string [x y z] x + y + z)
#'infixapp.core.works
```
but calling 'works' succeeds and 'fails' fails.

Apart from that, Thank you very much for the suggested solutions, i am currently using the second one and it is working fine!
