### ISSUE TITLE
It doesn't work with ClojureScript

### ISSUE THREAD

**Issue by dilvan1** [rm-hull/infix#23]
Tried to use in a pure clojureScript project. Doesn't work. Also, tried to use the source code, there are some functions not available in clojureScript.

**Comment by rm-hull** [comment]
So I think that is a copy/paste error in the _project.clj_ and _README.md_ - it was only ever targeted at clojure, but the macro should work against clojurescript (although I have never tested it).

Could you provide a code snippet of what you were trying to do?

I will look into seeing how easy it is to convert the files to cross-format .cljc and write some clojurescript tests.

**Comment by dilvan1** [comment]
I was able to make it work with ClojureScript, but then tried `(infix 4 / 4 *2)` and got 0.5. It should have been 2. It is executing the multiplication first, even though it comes last. It also happens with Clojure too (it returns 1/2).

**Comment by dilvan1** [comment]
About ClojureScript, the way it includes macros is different from Clojure, so maybe you can add a warning showing how to include it:

`(:require-macros [infix.macros :refer [infix]])`

**Comment by rm-hull** [comment]
Ok, I'll add a test and fix that operator precedence issue, and add a note about the require-macros into the README - thanks for taking the time reporting this issue

**Comment by rm-hull** [comment]
There should be a new version now with this fix in it: https://clojars.org/rm-hull/infix/versions/0.2.11

**Comment by dilvan1** [comment]
Thanks.
