### ISSUE TITLE
Support Clojurescript?

### ISSUE THREAD

**Issue by Frozenlock** [rm-hull/infix#28]
I tried to use the `from-string` macro, but it doesn't work in clojurescript.
The `infix` macro itself is a little shaky; it will throw an error when using functions from `infix.math.trig`.

Looking at the code, I see a few places that could be solved by using reader conditionals to dispatch to different functions when in clj or cljs.

However there's a dependency which would need to be ported to clojurescript as well : https://github.com/rm-hull/jasentaa

Is this something that is planned?

**Comment by rm-hull** [comment]
The `infix` macro _should_ work, but I take your point about the math functions.

`from-string` is another kettle of fish however, and probably would need jasentaa porting as you observed; something I hadn't contemplated or planned to do, but IIRC there is nothing in there that should be difficult to port to be cross-platform.

If you want to have a go at making jasentaa work on cljs, then I would be happy to merge it back in and release a new version

**Comment by Frozenlock** [comment]
Thanks, I'll take a look at `jasentaa` and come back at `infix` if I can add cljs support.

**Comment by Frozenlock** [comment]
Working on cljs support.
I'm faced with a little problem with how the library is using quoted aliases, rather than using the functions directly.

(See https://github.com/rm-hull/infix/blob/master/src/infix/core.clj#L30)

For a quick explanation of the problem : https://stackoverflow.com/questions/12020576/resolve-function-throws-an-error-in-clojurescript-but-not-clojure

Considering the aliases are already dealing with most of the operators, what is the purpose of this resolution? I can see an automatic resolution for clojure.core math operators, but we could still get the same effect simply by entering them manually in the alias map.

Could we switch to using the functions directly in the alias map, rather than only their symbols?

**Comment by Frozenlock** [comment]
Probably related : https://github.com/rm-hull/infix/issues/17

**Comment by rm-hull** [comment]
It’s been a while since I delved into the codebase, so I’d need to refresh myself first. It would make sense implementing a solution for #17 first though.

What problem have you got exactly? Can you share some code or the error you are getting?

Also, remember that all the rewrite function is doing is walking a nested list of symbols and reordering them, but along the way it tries to replace symbols in the map with the actual symbols from core. It would still need to process symbols if we elided the operator aliases

**Comment by rm-hull** [comment]
I will have a look at #17 now, and will try and use the `base-env` rather than the alias map

**Comment by Frozenlock** [comment]
I don't think `base-env` is better; it returns a map with with vars.

Here's the problem : 
```
Caused by: clojure.lang.ExceptionInfo: Assert failed: Argument to resolve must be a quoted symbol
(core/and (seq? quoted-sym) (= (quote quote) (first quoted-sym))) at line 100 src/cljc/infix/core.cljc {:file "src/cljc/infix/core.cljc", :line 100, :column 16, :tag :cljs/analysis-error}
```
From the stackoverflow link : 
> resolve doesn't exist in ClojureScript. In fact, ClojureScript does not have Vars.

Additionally, the advanced compilation will break this type of resolution.
(`clojure.core/+` could become `zza` in the compiled js)

So the point is that the whole var thing is a non-starter in clojurescript.
I also don't see the point of using it, as we can store functions directly in a map, rather than storing symbols. (But I might be missing a use case or two...)

```clj
;; storing symbols
{:plus 'clojure.core/+}
; => {:plus clojure.core/+}

;; storing functions
{:plus clojure.core/+}
;=> {:plus #function[clojure.core/+]}
```

**Comment by rm-hull** [comment]
What I was trying to allude to earlier, is that`infix` is a macro and will call `rewrite` with a list of symbols, e.g.:`(infix 1 + 2)` would just call `(rewrite '(1 + 2))` - you could get rid of the operator-alias mapping altogether but would still be dealing in symbols from the macro... could you provide a shim implementation for `bounded?` for cljs if `resolve` is not supported?

It just dawned on me that the base-env / var thing is a bit more complicated (or more likely, over-complicated) - maybe the base-env _can_ just be a map of keyword->functions, but might need to be constructed manually rather than with the `ns-publics` reflection

**Comment by Frozenlock** [comment]
Symbols from the macro are not a problem if they refer to a function in the alias map.
Yes, I'll try to come up with something.

**Comment by Frozenlock** [comment]
Here, this should run in a blank REPL

```clj
(def replacement-alias
  (atom
   {'+    +
    '-    -
    '/    /
    '*    *
    'ten   10}))

(def operator-precedence
  [+ - * /])


(defn replace-alias [term]
  (get @replacement-alias term term))

(defn- empty-arglist? [xs]
  (let [elem (fnext xs)]
    (and (seq? elem) (empty? elem))))

(defn rewrite
  "Recursively rewrites the infix-expr as a prefix expression, according to
   the operator precedence rules"
  [infix-expr]
  (cond
    (not (seq? infix-expr)) ;; -> pi
    (replace-alias infix-expr)

    (and (seq? (first infix-expr)) (= (count infix-expr) 1)) ;; -> ((2 + 3))
    (rewrite (first infix-expr))

    (empty? (rest infix-expr)) ;; -> (2)
    (first infix-expr)

    :else ;; -> (2 + 3)
    (let [infix-expr (map replace-alias infix-expr)]
      (loop [ops operator-precedence]
        (if-let [op (first ops)]
          (let [idx (.lastIndexOf ^java.util.List infix-expr op)]
            (if (pos? idx)
              (let [[expr1 [op & expr2]] (split-at idx infix-expr)]
                (list op (rewrite expr1) (rewrite expr2)))
              (recur (next ops))))

          (if (empty-arglist? infix-expr)
            (list (rewrite (first infix-expr)))
            (list (rewrite (first infix-expr)) (rewrite (next infix-expr)))))))))

```
Results :

```clj
(rewrite '(3 + 3 * 2))
;=> (#function[clojure.core/+] 3 (#function[clojure.core/*] 3 2))

(rewrite '(3 / 3 - 2))
;=> (#function[clojure.core/-] (#function[clojure.core//] 3 3) 2)

(rewrite '(ten + 2))
;=> (#function[clojure.core/+] 10 2)
```

Now that I look at `from-string`, it seems that it is *completely* unrelated to `infix/rewrite`.

**Comment by Frozenlock** [comment]
Good news, `from-string` already works with functions.
The `base-env` map already has some in it. https://github.com/rm-hull/infix/blob/master/src/infix/core.clj#L152-L159

**Comment by Frozenlock** [comment]
@rm-hull Could you point to me where the operator precedence is defined in the grammar?

**Comment by Frozenlock** [comment]
After much exploring, I've decided to go with Instaparse for my needs.
Turns out it can do pretty much everything out of the box.

I'd close this issue, but I don't know if supporting Clojurescript is on your roadmap, so I'll leave it up to you.
