### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by nlw0** [rm-hull/infix#31]
I am sorry, I am a complete newbie to Clojure, and I am really looking forward to use this library to help me out with my arithmetics. I just don't seem to be able to install it. How does that work?

I have a Leiningen project. I added infix as a dependency 

`  :dependencies [[org.clojure/clojure "1.8.0"]
                 [rm-hull/infix "0.3.3"]]`

I have a recent version of Leiningen, that the Readme says matters.

`$ lein --version
Leiningen 2.8.1 on Java 9.0.4 Java HotSpot(TM) 64-Bit Server VM
`

But then...

```
$ lein repl
nREPL server started on port 45235 on host 127.0.0.1 - nrepl://127.0.0.1:45235
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

jayray.core=> (refer 'infix.macros :only '[infix from-string base-env])

Exception No namespace: infix.macros  clojure.core/refer (core.clj:4104)
jayray.core=> Bye for now!

```

I must be missing a completely stupid, basic and obvious step, and I apologize in advance. But what is it that I am missing?

**Comment by rm-hull** [comment]
Hi - apologies for the delay, missed this issue (think I was away on holiday) ... anyway I think it might be something to do with trying it from the REPL - maybe `refer` doesnt work properly from the command line (it should in regular clojure code).

If you want to try it from the REPL, I suggest you try the following instead:

```clojure
user=> (use 'infix.macros)
nil
user=> (infix 3 + 5)
8
```

**Comment by rm-hull** [comment]
If that doesn't work, can you paste the output of running `ls -lR ~/.m2/repository/rm-hull/infix/` on the command line?

**Comment by vdikan** [comment]
I have same issue with `'use`, but it's not really an issue: usage of `'use` should be avoided by all means, and the symbols in question can be `require`-d, e.g.:
```
(ns something.core
  (:require [infix.core :only base-env]
            [infix.macros :as im]))

(im/infix 4 + 5) => 9
```
