### ISSUE TITLE
Logical and bitwise operators

### ISSUE THREAD

**Issue by dsbw** [rm-hull/infix#33]
I know it's no longer maintained, but I'm curious as to how the logical, bitwise and comparator operators are supposed to work. I've tried every combination I can think of:

```
((from-string "16 = 16"))
=> true
((from-string "16 > 16"))
Execution error (ParseException) at jasentaa.position/parse-exception-interop (position.cljc:45).
Failed to parse text at line: 1, col: 4
16 > 16
   ^

((from-string "16 || 16"))
Execution error (ParseException) at jasentaa.position/parse-exception-interop (position.cljc:45).
Failed to parse text at line: 1, col: 4
16 || 16

((from-string "16 or 16"))
Execution error (ParseException) at jasentaa.position/parse-exception-interop (position.cljc:45).
Failed to parse text at line: 1, col: 4
16 or 16
   ^
```

etc.

**Comment by rm-hull** [comment]
So first off - you're using the `from-string` form, and I seem to remember this is more restricted than the regular `infix` macro. I'm not sure whether this is documented clearly .. let me check.

In any regard, you can see from here: https://github.com/rm-hull/infix/blob/master/src/infix/grammar.clj#L163-L164 that there are a limited set of ops for the `from-string` form

**Comment by rm-hull** [comment]
I'm not actively developing any new code for this project, but if there is a compelling bug that needs fixing I would publish a new release. So i kinda just forgot to update the badge on the readme 😊

**Comment by dsbw** [comment]
Well, thanks for the speedy response! It's much appreciated.

What about the from-string forms requires the limitations, may I ask? Is it a parsing issue?

**Comment by rm-hull** [comment]
no i think it is probably just an omission on my part; it should be simple to add... i think the change should just be along the lines:

```clojure
(def mulop (binary-op "*" "/" "÷" "**" "%" ">>" ">>>" "<<" "=" "==" "!=" "<=" "<" ">" ">="))
(def addop (binary-op "+" "-" "|" "&" "||" "&&" "or" "and"))
```

**Comment by rm-hull** [comment]
What happens if you try:

```clojure
((from-string "or(16, 16)"))
```

?

**Comment by dsbw** [comment]
"or is not bound in environment"

**Comment by rm-hull** [comment]
See https://github.com/rm-hull/infix/commit/678a95464f11f471a8aa41cbdb600a251319baf6#diff-1f3b0b7dedcbe5d2bec7d22ff659086dd3d53f6103e5ea71b221d9df5f73802aR118-R126 for usage (not only `||` and `&&` are supported rather than the textual versions)

**Comment by dsbw** [comment]
Nice! Thank you!
