### ISSUE TITLE
Precedence error for **

### ISSUE THREAD

**Issue by dsbw** [rm-hull/infix#34]
From the Wiki (pasting in the 2s as superscript didn't work, so I prefaced the 2 with **, as it would be in infix):

> When exponents were introduced in the 16th and 17th centuries, they were given precedence over both addition and multiplication, and could be placed only as a superscript to the right of their base.[1] Thus `3 + 5**2 = 28` and `3 × 5**2 = 75`.

Using infix from-string:

```
((from-string "3 + 5**2"))
=> 28.0
((from-string "3 * 5**2"))
=> 225.0
((from-string "10 / 10**2"))
=> 1.0
```

Looks like * and / are given precedence over **.

**Comment by rm-hull** [comment]
Yes, i think you are right .. will look into this

**Comment by rm-hull** [comment]
@dsbw: I will make a release for this after fixing up a few other open tickets
