### ISSUE TITLE
Basic operator precedence

### ISSUE THREAD

**Issue by eivindw** [rm-hull/infix#5]
Hi, thanks for creating a great library! Very useful for human-readable math-expressions!
Not sure if this is an issue, but it confused me. Using several basic operators after each-other like this:
`(infix 3 - 2 - 1)`
You would expect 3 - 2 - 1 to evaluate to 0, right? But default precedence in the library makes it evaluate to 2 - since it is evaluated as 3 - (2 - 1) = 3 - 1 = 2
Fixing this would make the library more useful for me. As some of the reason for using this is to show the expression more or less as it is given in a formula description - avoiding the std. Clojure grouping of expressions.

You think this could be done? I can try to look at it myself in a pull-request, but I thought you could probably solve it or answer the question much faster :)

Edit: The problem is easily testable:
`(is (= 0 (infix 3 - 2 - 1)))`

> FAIL in (basic-arithmetic) (macros_tests.clj:35)
expected: (= 0 (infix 3 - 2 - 1))
  actual: (not (= 0 2))

**Comment by rm-hull** [comment]
Hi, I'm away on holiday at the moment - due back on 7th April, so I'll look into it then. Of course, if you want to fork and submit a PR in the meantime that would be much appreciated.

I think you're right, it should probably equal zero. In the meantime, you should be able use parens:

    (infix (3 - 2) - 1)

The library is still quite young, so feedback like this is great :)

**Comment by rm-hull** [comment]
Have pushed some changes to make this work as you described. 
I've pulled in the failing test case from your fork... if you can think of any extra tests that would be worthwhile, then any PRs would be gladly accepted.

Will update the version and push to clojars in the next day or so.

**Comment by eivindw** [comment]
Nice. Thank you for fixing :+1:
